CREATE TABLE student_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id VARCHAR(40) NOT NULL UNIQUE,
    department VARCHAR(120) NOT NULL,
    program VARCHAR(120) NOT NULL,
    year_of_study INTEGER NOT NULL,
    user_id BIGINT NOT NULL UNIQUE,
    CONSTRAINT fk_student_profiles_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_student_profiles_year CHECK (year_of_study > 0)
);

CREATE TABLE offices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    office_name VARCHAR(120) NOT NULL UNIQUE,
    description TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
