CREATE TABLE clearance_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(30) NOT NULL,
    comment TEXT,
    clearance_request_id BIGINT NOT NULL,
    office_id BIGINT NOT NULL,
    reviewed_by_id BIGINT,
    reviewed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_clearance_steps_request FOREIGN KEY (clearance_request_id) REFERENCES clearance_requests (id),
    CONSTRAINT fk_clearance_steps_office FOREIGN KEY (office_id) REFERENCES offices (id),
    CONSTRAINT fk_clearance_steps_reviewed_by FOREIGN KEY (reviewed_by_id) REFERENCES users (id),
    CONSTRAINT chk_clearance_steps_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'WAITING')),
    CONSTRAINT uq_clearance_steps_request_office UNIQUE (clearance_request_id, office_id)
);

CREATE TABLE attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    uploaded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    clearance_request_id BIGINT NOT NULL,
    CONSTRAINT fk_attachments_request FOREIGN KEY (clearance_request_id) REFERENCES clearance_requests (id)
);
