CREATE TABLE approval_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(80) NOT NULL,
    note TEXT,
    action_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actor_id BIGINT NOT NULL,
    clearance_request_id BIGINT NOT NULL,
    clearance_step_id BIGINT,
    CONSTRAINT fk_approval_logs_actor FOREIGN KEY (actor_id) REFERENCES users (id),
    CONSTRAINT fk_approval_logs_request FOREIGN KEY (clearance_request_id) REFERENCES clearance_requests (id),
    CONSTRAINT fk_approval_logs_step FOREIGN KEY (clearance_step_id) REFERENCES clearance_steps (id)
);

CREATE TABLE blacklisted_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(1000) NOT NULL UNIQUE,
    expiry_date TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
